import "./globals.css";
import { Aldrich, Orbitron, Rajdhani } from "next/font/google";

const aldrich = Aldrich({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-aldrich",
  display: "swap",
});
const orbitronr = Orbitron({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-orbitronr",
  display: "swap",
});
const rajdhani = Rajdhani({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-rajdhani",
  display: "swap",
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${aldrich.variable} ${orbitronr.variable} ${rajdhani.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
